import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Notificate } from "@/shared/ui/Notificate";
import { Footer } from "@/widgets/footer";
import { Header } from "@/widgets";

const inter = Inter({
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${inter.className}`}>
      <body>
        <Header />
        <Notificate />
        {children}
        <Footer />
      </body>
    </html>
  );
}
